<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    <RootNamespace>Adact.Tests.Common</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit" Version="2.9.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Adact.Engine\Adact.Engine.csproj" />
  </ItemGroup>
</Project>
